BlogItsy/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.home, name="home"),
    # url(r'^(?P<slug>[\w-]+)/$', views.home, name="detail1"),
    url(r'^about/$', views.about, name="about"),
    url(r'^blog/$', views.blog,),
    url(r'^contact/$', views.contact,name="contact"),
    url(r'^articles/', include('articles.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

articles/urls.py
from django.conf.urls import url,include
from . import views

app_name = 'articles'

urlpatterns = [
    url(r'^$', views.blog_list, name="list"),
    url(r'^(?P<slug>[\w-]+)/$', views.blog_detail, name="detail"),
    

]

articles/models.py
from django.db import models
from tinymce.models import HTMLField
from django.contrib.auth import get_user_model

# Create your models here.
User = get_user_model()

class Author(models.Model):
    user            = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_picture = models.ImageField()
    aboutme         = models.TextField(blank = True)

    def __str__(self):
        return self.user.username


class Article(models.Model):
    title           = models.CharField(max_length=100)
    slug            = models.SlugField()
    body            = models.TextField()
    image_1         = models.FileField(default='default.jpg', blank=True)
    image_2         = models.FileField(default='default.jpg', blank=True)
    image_3         = models.FileField(default='default.jpg', blank=True)
    date            = models.DateTimeField(auto_now_add=True)
    comment_count   = models.IntegerField(default=0)
    content         = HTMLField()
    author          = models.ForeignKey(Author, on_delete=models.CASCADE)
    featured        = models.BooleanField(default=False)

    def __str__(self):
        return self.title

class Signup(models.Model):
    name        = models.CharField(max_length=100)
    email       = models.EmailField()
    message     = models.TextField(blank = True)
    timestamp   = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email

BlogItsy/views.py
from django.http import HttpResponse
from django.shortcuts import render
from articles.models import Article,Author,Signup

def home(request):
    featured    = Article.objects.filter(featured=True)
    latest      = Article.objects.order_by('-timestamp')[0:3]
    articles    = Article.objects.all().order_by('date')
    hauthor      = Author.objects.all()

    # article1     = Article.objects.get(slug=slug)

    context = {
        'featured': featured,
        'latest': latest,
        'blog_list': articles,
        'hauthor': hauthor
    }
    return render(request, 'index.html',context)

def about(request):
    author      = Author.objects.all()
    return render(request, 'about.html',{'author': author})

def blog(request):
    return render(request, 'blog.html')

def contact(request):

    if request.method == 'POST':
        name = request.POST["name"]
        email = request.POST["email"]
        message = request.POST["message"]
        new_signup = Signup()
        new_signup.name = name
        new_signup.email = email
        new_signup.message = message
        new_signup.save()

    return render(request, 'contact.html')

articles/views.py
from django.shortcuts import render
from .models import Article,Author
from django.http import HttpResponse

def blog_list(request):
    blogs = Article.objects.all().order_by('date')
    author      = Author.objects.all()
    context = {
        'barticles':blogs,
        'bauthor': author
    }
    return render(request,'articles/blog.html',context)

def blog_detail(request, slug):
    article = Article.objects.get(slug=slug)
    author      = Author.objects.all()

    context = {
        'article': article,
        'author': author
    }
    return render(request,'articles/single.html',context)

articles/templates/articles/blog.html
{% extends 'base.html' %}
{% load static from staticfiles %}
<!doctype html>

{% block content %}

<div class="wrap full-wrap">
    <div class="main-wrap">
        <section class="main main-archive">

            <article class="post result">
                <div class="inner">
                    <h1 class="searching">Blog</h1>
                    <p>A Great description would go in here</p>
                </div>
            </article>
              {% for article in barticles %}
            <div class="loop">
                <article class="post format-gallery post_format-post-format-gallery">



                    <a href="{% url 'articles:detail' slug=article.slug %}"
                       title="{{ article.title }}">
                        <div class="part-gallery">
                            <div class="flexslider">
                                <ul class="slides">

                                    <li><span class="post-image"><img src="{{ article.image_1.url }}"
                                                                      alt="Run-3"/></span></li>
                                    <li><span class="post-image"><img src="{{ article.image_2.url }}"
                                                                      alt="Run-1"/></span></li>
                                    <li><span class="post-image"><img src="{{ article.image_3.url }}"
                                                                      alt="Run-2"/></span></li>
                                </ul>
                            </div>
                        </div>

                    </a>

                    <div class="inner">

                        <h2 class="entry-title">
                              <div class="article">
                                  <h2><a href="{% url 'articles:detail' slug=article.slug %}">{{ article.title }}</a></h2>

                        </h2>
                        <ul class="meta top">
                            <li class="time">
                                <a href="{% url 'articles:detail' slug=article.slug %}"
                                   title="{{ article.title }}">
                                    <time class="post-date updated" datetime="2015-02-01">{{ article.date }}</time>
                                </a></li>

                            <li class="comments post-tags">
                                <a href="#">{{ article.comment_count }} Comments</a></li>

                            <li class="author-m post-tags">
                                By <span class="vcard author post-author"><span class="fn"><a
                                    href="{% url 'about' %}"
                                    title="Posts by {{ article.author }} " rel="author">{{ article.author }}</a></span></span>
                            </li>

                        </ul>
                        <div class="post-content">
                            <p>{{ article.content }}</p>
                            <blockquote><p>“{{ article.body }}”<cite>{{ article.author }}</cite></p></blockquote>
                            <p><a
                                        href="{% url 'articles:detail' slug=article.slug %}"
                                        class="more-link">Read More</a></p>
                        </div>


                        <ul class="meta bottom">


                            <li class="cat post-tags">Saved: <a
                                    href="{% url 'articles:list' %}">Blog</a>,
                                <a href="#">Fitness</a>
                            </li>

                        </ul>

                    </div>



                </article>
            </div>
              {% endfor %}
        </section>
    </div><!-- /main-wrap -->
</div><!-- /wrap -->

{% endblock content %}

articles/templates/articles/single.html
{% extends 'base.html' %}
{% load static from staticfiles %}
<!doctype html>

{% block content %}
<!-- <div class="article-detail">
  <div class="article">
    <img src="{{ article.image_1.url }}" />
    <h2>{{ article.title }}</h2>
    <p>{{ article.body }}</p>
    <p>{{ article.date }}</p>
  </div>
</div> -->



<div class="wrap full-wrap">
    <div class="main-wrap">
        <section class="main">


            <article class="post has-post-thumbnail">

  		        <span class="post-image">
                    <img width="916" height="611" src="{{ article.image_1.url }}" alt="">
  		        </span>


                <div class="inner">

                    <h1 class="entry-title">{{ article.title }}</h1>
                    <ul class="meta top">
                        <li class="time">
                            <time class="post-date updated" datetime="2015-02-02">{{ article.date }} </time>
                        </li>

                        <li class="comments">
                            <a href="#">{{ article.comment_count }} Comments</a>
                        </li>

                        <li class="author-m">
                            By <span class="vcard author"><span class="fn"><a href="{% url 'about' %}" title="Post by {{ article.author }}" rel="author">{{ article.author }}</a></span></span>
                        </li>

                    </ul>
                    <div class="post-content">
                        <p>{{ article.content }}</p>
                        <blockquote><p>“{{ article.body }}”<cite>{{ article.author }}</cite></p></blockquote>

                    </div>


                    <ul class="meta bottom">
                        <li class="cat">Saved:  <a href="{% url 'articles:list' %}">Blog</a>, <a href="#">Cute</a></li>
                    </ul>

                </div>
            </article>

            <nav class="pagination">
                <ul>
                    <li class="older-posts">
                        <span><a href="{% url 'articles:list' %}" rel="prev"><i class="fa fa-chevron-left"></i> <span class="i">Prev</span></a></span>
                    </li>
                    <li class="share-link">
                        <a href="#"><i class="fa fa-share-alt"></i><span class="i">Share</span></a>
                    </li>
                    <li class="newer-posts">
                        <span class="inactive"><span class="i">Next</span> <i class="fa fa-chevron-right"></i></span>
                    </li>

                </ul>
            </nav>
          <aside class="author-wrap">
                <span class="author-avatar"><img alt="" src="{{ author.profile_picture.url }}" class="avatar avatar-200 photo" height="200" width="200"></span>
                <div class="author-bio">
                  {% for aut in author %}
                    <h4><a href="{% url 'about' %}">{{ aut.user }}</a></h4>
                    <p>{{ aut.aboutme }}</p>
                    <div class="author-socials-wrap">

                        <a class="author-socials" href="http://twitter.com/" target="_blank"><i class="fa fa-twitter"></i><span>Twitter</span></a>
                        <a class="author-socials" href="http://facebook.com/" target="_blank"><i class="fa fa-facebook"></i><span>Facebook</span></a>
                        <a class="author-socials" href="https://www.instagram.com/" target="_blank"><i class="fa fa-instagram"></i><span>Instagram</span></a>
                        <a class="author-socials" href="https://in.pinterest.com/" target="_blank"><i class="fa fa-pinterest"></i><span>Pinterest</span></a>
                        <a class="author-socials" href="#" target="_blank"><i class="fa fa-flickr"></i><span>Flickr</span></a>
                        <a class="author-socials" href="http://dejo.pythonanywhere.com/" target="_blank"><i class="fa fa-link"></i><span>Website</span></a>

                    </div>
                    {% endfor %}
                </div>

            </aside>
          <div class="related-posts">

                <h5>Related</h5>

                <div class="posts">

                    <aside class="related post has-post-thumbnail">

  		                <span class="post-image">
                            <a href="#" title="The Apothecary">
                                <img width="468" height="468" src="images/Apothecary.jpg" alt=""></a>
                        </span>


                        <div class="inner">

                            <h6 class="entry-title">

                                <a href="#" title="The Apothecary">

                                    The Apothecary
                                </a>
                                <ul class="meta top">
                                    <li class="time">
                                        <time class="post-date updated" datetime="2015-01-31">January 31, 2015</time>
                                    </li>
                                </ul>

                            </h6>

                        </div>
                    </aside>


                    <aside class="related post has-post-thumbnail">

                        <span class="post-image">
                            <a href="#" title="The Flowers">
                                <img width="468" height="468" src="images/Flowers.jpg" alt="" ></a>
                        </span>


                        <div class="inner">

                            <h6 class="entry-title">

                                <a href="#" title="The Flowers">The Flowers</a>
                                <ul class="meta top">
                                    <li class="time">
                                        <time class="post-date updated" datetime="2015-01-25">January 25, 2015</time>
                                    </li>
                                </ul>

                            </h6>

                        </div>
                    </aside>

                    <aside class="related post has-post-thumbnail">

                        <span class="post-image">
                            <a href="#" title="The Sunny Day">
                                <img width="468" height="468" src="images/Sun.jpg" alt="">
                            </a>
                        </span>


                        <div class="inner">

                            <h6 class="post-title entry-title">

                                <a href="#" title="The Sunny Day">The Sunny Day</a>
                                <ul class="meta top">
                                    <li class="time">
                                        <time class="post-date updated" datetime="2015-01-21">January 21, 2015</time>
                                    </li>
                                </ul>

                            </h6>

                        </div>
                    </aside>


                </div></div>
          <div class="comments-wrapper">

                <div id="comments" class="inner">

                    <div class="comments-inner"><h3 id="respond-title">Comments (0)</h3></div>

                    <aside class="comments">
                    </aside>

                    <div id="respond" class="comment-respond">
                        <h3 id="reply-title" class="comment-reply-title">Leave a comment <small><a rel="nofollow" id="cancel-comment-reply-link" href="#respond" style="display:none;">Cancel reply</a></small></h3>
                        <form>
                            <p>Your email address will not be published. Required fields are marked <span class="required">*</span></p>
                            <p><label for="comment">Comment</label><textarea id="comment" name="comment" cols="45" rows="8" aria-required="true" placeholder="Comment"></textarea></p><p class="comment-form-author"><label class="hidden" for="author">Name</label> <span class="required hidden">*</span><input id="author" name="author" type="text" value="" size="30" aria-required="true" placeholder="Name"></p>
                            <p><label for="email">Email</label> <span class="required ">*</span><input id="email" name="email" type="text" value="" size="30" aria-required="true" placeholder="Email"></p>
                            <p><label for="url">Website</label><input id="url" name="url" type="text" value="" size="30" placeholder="Website"></p>
                            <p class="form-submit"><input name="submit" type="submit" id="submit" class="submit" value="Post Comment"></p>
                        </form>
                    </div><!-- #respond -->

                </div>

            </div>
        </section>
    </div><!-- /main-wrap -->
</div><!-- /wrap -->

{% endblock %}

templates/about.html
{% extends 'base.html' %}
{% load static from staticfiles %}

{% block content %}
<div class="wrap full-wrap">
    <div class="main-wrap">

        <section class="main">
            <article class="post page">
               {% for ath in author %}
                <div class="inner">
                    <h1>About me</h1>
                    <div class="post-content">
                        <p><img class="size-full alignleft rounded" src="{{ ath.profile_picture.url }}" alt=".." width="300" height="300">
                          "{{ ath.aboutme }}"</p>

                            <p>
                                <a target="_self" class="social twitter black" href="#"> Twitter </a>
                                <a target="_self" class="social facebook black" href="#"> Facebook&nbsp;</a>
                                <a target="_self" class="social instagram black" href="#">&nbsp;instagram&nbsp;</a>
                                <a target="_self" class="social flickr black" href="#"> flickr&nbsp;</a>
                            </p>

                    </div>
                </div>
               {% endfor %}
            </article>
            <div class="border"></div>
        </section>
    </div><!-- /main-wrap -->
</div><!-- /wrap -->
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html class="home blog no-js" lang="en-US">
  {% include "head.html" %}
  <body class="home sticky-menu sidebar-off" id="top">

      {% include 'header.html' %}
      {% block content %}
      {% endblock content %}
      {% include 'footer.html' %}

  </body>
</html>

templates/footer.html
{% load static from staticfiles %}

<div class="footer-widgets widget-count-4">

    <div class="wrap">

        <div class="mt-about-you-widget">

            <div class="widget footer">
               {% for ath in hauthor %}
                <img class="mt-about-avatar" src="{{ ath.profile_picture.url }}" alt=".."/>


                <h4>{{ ath.user }}</h4>

                <div class="mt-about-bio">
                    <p>Hi, my name is Denzil and I&#039;m  a serial blogger. I love life and more
                    than anything in the whole wide world, I love taking photographs. Oh and did I mention, I quite like
                    traveling?</p>
                </div>

                {% endfor %}
            </div>

        </div>

<!-- ----------------------------------------------------         -->


        <div class="widget footer"><h4>Recent Posts</h4>

            <ul>
                <li>
                    <a href="#">{{ article.title }}</a>
                </li>
                <li>
                    <a href="#">Running through Chicago</a>
                </li>
                <li>
                    <a href="#">The Apothecary</a>
                </li>
                <li>
                    <a href="#">The Flowers</a>
                </li>
                <li>
                    <a href="#">The Sunny Day</a>
                </li>
            </ul>

        </div>
        <div class="widget footer"><h4>Categories</h4>
            <ul>
                <li class="cat-item cat-item-6">
                    <a href="{% url 'articles:list' %}" title="A cute little description would go in here">Blog</a>
                </li>
                <li class="cat-item cat-item-7">
                    <a href="#" title="A cute little description would go in here">Cute</a>
                </li>
                <li class="cat-item cat-item-8">
                    <a href="#">Fitness</a>
                </li>
                <li class="cat-item cat-item-9">
                    <a href="#">Fun</a>
                </li>
            </ul>
        </div>
        <div class="widget footer"><h4>Gallery</h4>
            <div class="textwidget">
                <img src="{% static 'images/gallery.png' %}" alt="">
            </div>
        </div>
    </div>

</div>


<footer class="footer">
    <div class="footer-wrap">
        <div id="footer-text">&copy; 2020
            Designed by <a href="https://www.linkedin.com/in/arun-kumar-7650a012b/" target="_blank">Arun</a>.</div>

        <a href="#top" id="btt">Top <i class="fa fa-chevron-up"></i></a>
    </div>
</footer>

templates/head.html
{% load static from staticfiles %}

<head>
  <title>MyBlog</title>

  <meta charset="UTF-8"/>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
        type="text/css" media="all"/>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Amatic+SC%3A400%2C700%7CLato%3A400%2C700%2C400italic%2C700italic&amp;ver=4.9.8"
        type="text/css" media="screen"/>
  <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="screen"/>
  <link rel="stylesheet" href="{% static 'css/print.css' %}" type="text/css" media="print"/>
  <script src="{% static 'js/jquery-3.0.0.min.js' %}"></script>
  <script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>

  <script>var ie9 = false;</script>
  <script src="{% static 'js/global-plugins.min.js' %}"></script>
  <script src="{% static 'js/main.js' %}"></script>


</head>

templates/header.html
<header class="header">

    <div class="header-wrap">

        <div class="logo plain logo-left">
            <div class="site-title">
                <a href="{% url 'home' %}" title="Go to Home">DeJo</a>
            </div>
        </div><!-- /logo -->


        <nav id="nav" role="navigation">
            <div class="table">
                <div class="table-cell">
                    <ul id="menu-menu-1">
                        <li class="menu-item">
                            <a href="{% url 'home' %}">Home</a></li>
                        <li class="menu-item">
                            <a href="{% url 'about' %}">About me</a></li>
                        <!-- <li class="menu-item">
                            <a href="#">Dropdown</a>
                            <ul class="sub-menu">
                                <li class="menu-item">
                                    <a href="#">Cute</a></li>
                                <li class="menu-item">
                                    <a href="#">Fun</a></li>
                                <li class="menu-item">
                                    <a href="#">Fitness</a>
                                </li>
                            </ul>
                        </li> -->
                        <li class="menu-item">
                            <a href="{% url 'articles:list' %}">Blog</a>
                            <!-- <ul class="sub-menu">
                                <li class="menu-item">
                                    <a href="single.html">Single</a></li>
                            </ul> -->
                        </li>
                        <!-- <li class="menu-item">
                            <a href="typography.html">Typography</a></li> -->
                        <li class="menu-item">
                            <a href="{% url 'contact' %}">Contact me</a></li>
                        <li class="menu-inline menu-item">
                            <a title="Twitter" href="http://twitter.com/">
                                <i class="fa fa-twitter"></i><span class="i">Twitter</span>
                            </a></li>
                        <li class="menu-inline menu-item">
                            <a title="Facebook" href="http://www.facebook.com/">
                                <i class="fa fa-facebook"></i><span class="i">Facebook</span>
                            </a></li>
                        <li class="menu-inline menu-item">
                            <a title="Whatsapp" href="#"><i class="fa fa-whatsapp"></i><span class="i">Whatsapp</span></a>
                        </li>
                        <li class="menu-inline menu-item">
                            <a title="Instagram" href="https://www.instagram.com/">
                                <i class="fa fa-instagram"></i><span class="i">Instagram</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- <a href="#nav" class="menu-trigger"><i class="fa fa-bars"></i></a> -->

        <!-- <a href="#topsearch" class="search-trigger"><i class="fa fa-search"></i></a> -->

    </div>

</header>

templates/index.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% block content %}


<div class="hero" style="background-image: url({% static 'images/leader.jpg' %}); text-align:right;">
    <div class="hero-inner">
        <div class="inner">
            <h1><span class="border border-top border-bottom">DeJo</span></h1>
            <div class="hero-line-one"></div>
            <div class="hero-line-two"><span class="border border-bottom"><a href="{% url 'about' %}" style="color:#FFF;">the Explorer</a></span></div>
        </div>

        <a class="more-arrow" href="#content"><i class="fa fa-chevron-down"></i><span>Scroll Down</span></a>

    </div>
</div>


<div class="home-sticky" id="content">

    <h2 class="home-sticky-title">my fave moments</h2>

        <div class="featured">
        {% for obj in featured %}

            <div class="sticky-inner">

                <aside class="home-sticky-post post has-post-thumbnail sticky">

                  <div class="obj">


          		    <span class="post-image">
          				<a href="{% url 'articles:detail' slug=obj.slug %}">
          				<img width="502" height="502" src="{{ obj.image_1.url }}"
                             class="attachment-sticky size-sticky" alt=""/>
          				</a>
          		    </span>

                    <div class="inner">
                        <h3 class="entry-title">
                            <a href="{% url 'articles:detail' slug=obj.slug %}">{{ obj.title }}</a>
                        </h3>

                        <ul class="meta top">
                            <li class="time">
                                <a href="{% url 'articles:detail' slug=obj.slug %}">
                                    <time class="post-date updated" datetime="2015-02-02">{{ obj.date }}</time>
                                </a>
                            </li>
                        </ul>
                    </div>

                    </div>
                </aside>
            </div>

        {% endfor %}
        </div>


<div class="wrap full-wrap">
    <div class="main-wrap">
        <section class="main main-archive">
          {% for article in blog_list %}
            <div class="loop">

                <article class="post format-gallery post_format-post-format-gallery">


                    <a href="{% url 'articles:detail' slug=article.slug %}"
                       title="{{ article.title }}">
                        <div class="part-gallery">
                            <div class="flexslider">
                                <ul class="slides">

                                    <li><span class="post-image"><img src="{{ article.image_1.url }}"
                                                                      alt="Run-3"/></span></li>
                                    <li><span class="post-image"><img src="{{ article.image_2.url }}"
                                                                      alt="Run-1"/></span></li>
                                    <li><span class="post-image"><img src="{{ article.image_3.url }}"
                                                                      alt="Run-2"/></span></li>
                                </ul>
                            </div>
                        </div>

                    </a>

                    <div class="inner">

                        <h2 class="entry-title">
                            <a href="{% url 'articles:detail' slug=article.slug %}"
                               title="{{ article.title }}">
                                {{ article.title }} </a>
                        </h2>
                        <ul class="meta top">
                            <li class="time">
                                <a href="{% url 'articles:detail' slug=article.slug %}"
                                   title="{{ article.title }}">
                                    <time class="post-date updated" datetime="2015-02-01">{{ article.date }}</time>
                                </a></li>

                            <li class="comments post-tags">
                                <a href="{% url 'articles:detail' slug=article.slug %}">{{ article.comment_count }} Comments</a></li>

                            <li class="author-m post-tags">
                                By <span class="vcard author post-author"><span class="fn"><a
                                    href="{% url 'about' %}"
                                    title="Posts by {{ article.author }}" rel="author">{{ article.author }}</a></span></span>
                            </li>

                        </ul>
                        <div class="post-content">
                            <p>{{ article.content }}</p>
                            <blockquote><p>“{{ article.body }}”<cite>{{ article.author }}</cite></p></blockquote>
                            <p><a
                                        href="{% url 'articles:detail' slug=article.slug %}"
                                        class="more-link">Read More</a></p>
                        </div>


                        <ul class="meta bottom">


                            <li class="cat post-tags">Saved: <a
                                    href="#">Blog</a>,
                                <a href="#">Fitness</a>
                            </li>


                        </ul>

                    </div>
                </article>

            </div>
            {% endfor %}
        </section>
    </div><!-- /main-wrap -->
</div><!-- /wrap -->

</div>

<div id="topsearch">
    <!-- <div class="table">
        <div class="table-cell">
            <form role="search" method="get" class="searchform" action="{% url 'home' %}">
                <div>
                    <input type="text" value="" name="s" class="s" placeholder="Type and hit enter"/>
                    <input type="submit" class="searchsubmit" value="Search"/>
                </div>
            </form>
        </div>
    </div> -->
    <a href="#topsearch" class="search-trigger"><i class="fa fa-times"></i></a>
</div>
{% endblock content %}